---
swagger: "2.0"
info:
  description: "This is a RESTful API for getting quotes from characters in the famous\
    \ series Game of Thrones."
  version: "1.0.0"
  title: "GOT Quotes API"
  termsOfService: ""
  contact:
    url: "https://github.com/adamichelle/got-quotes-api"
  license:
    name: "ISC"
    url: "https://github.com/adamichelle/got-quotes-api/blob/master/LICENSE"
host: "https://gameofthrones-quotes-api.herokuapp.com"
basePath: "/api/v1"
tags:
- name: "quotes"
  description: "Everything about the quotes"
schemes:
- "https"
paths:
  /quotes:
    get:
      tag: 
        - "quotes"
      summary: Get all quotes.
      description: Get an array of all quote objects.
      responses:
        200:
          description: Sucessful retrieval of array of quote objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'success'
                  data:
                    type: array
                    items:
                      $ref: "#/definitions/Quote"
        400:
          description: Error retrieving array of quote objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'error'
                  error:
                    type: string
                    example: 'unable to retrieve from db'
  /quotes/:quoteId:
    get:
      tag: 
        - "quotes"
      summary: Get specific quote using the quote 'id' property.
      description: Get a single quote object using the quote 'id' property.
      responses:
        200:
          description: Sucessful retrieval of specific quote with the specified quote 'id'.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'success'
                  data:
                    type: object
                    $ref: "#/definitions/Quote"
        400:
          description: Error retrieving specific quote with the specified quote 'id'.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'error'
                  error:
                    type: string
                    example: 'No quote with id of 119 found'
  /quote:
    get:
      tag:
        - "quotes"
      Summary: Get a random quote
      description: Get a single quote object randomly
      responses:
        200:
          description: Successful retrival of random quote object
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'success'
                  data:
                    type: object
                    $ref: "#/definitions/Quote"
        400:
          description: Error retrieving random quote object
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'error'
                  error:
                    type: string
                    example: 'unable to retrieve from db'
definitions:
  Quote:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      character:
        type: "string"
        example: "Jon Snow"
      quote:
        type: "string"
        example: "A girl is Arya Stark of Winterfell. And I'm going home."
    xml:
      name: "Quote"
